  version: 2
  jobs:
    build:
      docker:
        - image: reactcommunity/node-ci:8.4.0-0 # custom image -- includes ocaml, libelf1, Yarn
      parallelism: 2
      working_directory: ~/jigsaw-component-library
      steps:
        - checkout
        - restore_cache:
            # cache by branch + package.json, by branch, and then master
            keys:
              - v3-jigsaw-component-library-{{ .Branch }}-{{ checksum "package.json" }}
              - v3-jigsaw-component-library-{{ .Branch }}
              - v3-jigsaw-component-library-master
        - run: yarn # install root deps
        # - run: ./scripts/test.sh # run tests
        - setup_remote_docker
        - deploy:
            command: |
                VER="17.03.0-ce"
                curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
                tar -xz -C /tmp -f /tmp/docker-$VER.tgz
                mv /tmp/docker/* /usr/bin
                yarn global add expo-cli && cd example && yarn
                for user in "draftbit" "peterpme" "donald" "bluerssen"; do
                  eval EXPO_PASS='$'EXPO_${user}_PASSWORD
                  expo-cli login -u $user -p $EXPO_PASS --non-interactive
                  expo-cli publish --release-channel "${CIRCLE_SHA1}";
                done;
        - save_cache:
            key: v3-jigsaw-component-library-{{ .Branch }}-{{ checksum "package.json" }}
            paths:
              - ~/.cache/yarn
              # - ~/jigsaw-component-library/examples/NavigationPlayground/node_modules
              # - ~/jigsaw-component-library/examples/ReduxExample/node_modules
  notify:
    webhooks:
      - url: https://draftbit-slack-webhooks.herokuapp.com/github/snack-preview
